import difflib


LANGUAGES = {
    "abk": "Abkhaz",
    "ace": "Acehnese",
    "ach": "Acholi",
    "aar": "Afar",
    "af": "Afrikaans",
    "sq": "Albanian",
    "alz": "Alur",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "as": "Assamese",
    "ava": "Avar",
    "awa": "Awadhi",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "ban": "Balinese",
    "bal": "Baluchi",
    "bm": "Bambara",
    "bci": "Baoulé",
    "bak": "Bashkir",
    "eu": "Basque",
    "btx": "Batak Karo",
    "bts": "Batak Simalungun",
    "bbc": "Batak Toba",
    "be": "Belarusian",
    "bem": "Bemba",
    "bn": "Bengali",
    "bew": "Betawi",
    "bho": "Bhojpuri",
    "bik": "Bikol",
    "bs": "Bosnian",
    "bre": "Breton",
    "bg": "Bulgarian",
    "bua": "Buryat",
    "yue": "Cantonese",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "cha": "Chamorro",
    "che": "Chechen",
    "zh": "Chinese",
    "zh-cn": "Chinese (Simplified)",
    "zh-tw": "Chinese (Traditional)",
    "chk": "Chuukese",
    "chv": "Chuvash",
    "co": "Corsican",
    "crh": "Crimean Tatar",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "fa-af": "Dari",
    "dv": "Dhivehi",
    "din": "Dinka",
    "doi": "Dogri",
    "dom": "Dombe",
    "nl": "Dutch",
    "dyu": "Dyula",
    "dzo": "Dzongkha",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "fao": "Faroese",
    "fij": "Fijian",
    "fil": "Filipino (Tagalog)",
    "fi": "Finnish",
    "fon": "Fon",
    "fr": "French",
    "fy": "Frisian",
    "fur": "Friulian",
    "ful": "Fulani",
    "gaa": "Ga",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian Creole",
    "cnh": "Hakha Chin",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "iw": "Hebrew",
    "hil": "Hiligaynon",
    "hi": "Hindi",
    "hmn": "Hmong",
    "hu": "Hungarian",
    "hrx": "Hunsrik",
    "iba": "Iban",
    "is": "Icelandic",
    "ig": "Igbo",
    "ilo": "Ilocano",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "jam": "Jamaican Patois",
    "ja": "Japanese",
    "jv": "Javanese",
    "jw": "Javanese",
    "kac": "Jingpo",
    "kal": "Kalaallisut",
    "kn": "Kannada",
    "kau": "Kanuri",
    "pam": "Kapampangan",
    "kk": "Kazakh",
    "kha": "Khasi",
    "km": "Khmer",
    "cgg": "Kiga",
    "kik": "Kikongo",
    "rw": "Kinyarwanda",
    "ktu": "Kituba",
    "trp": "Kokborok",
    "kom": "Komi",
    "gom": "Konkani",
    "ko": "Korean",
    "kri": "Krio",
    "ku": "Kurdish",
    "ckb": "Kurdish (Sorani)",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "ltg": "Latgalian",
    "la": "Latin",
    "lv": "Latvian",
    "lij": "Ligurian",
    "lim": "Limburgish",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lmo": "Lombard",
    "lg": "Luganda",
    "luo": "Luo",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "mad": "Madurese",
    "mai": "Maithili",
    "mak": "Makassar",
    "mg": "Malagasy",
    "ms": "Malay",
    "ms-arab": "Malay (Jawi)",
    "ml": "Malayalam",
    "mt": "Maltese",
    "mam": "Mam",
    "glv": "Manx",
    "mi": "Maori",
    "mr": "Marathi",
    "mah": "Marshallese",
    "mwr": "Marwadi",
    "mfe": "Mauritian Creole",
    "mhr": "Meadow Mari",
    "mni-mtei": "Meiteilon (Manipuri)",
    "min": "Minang",
    "lus": "Mizo",
    "mn": "Mongolian",
    "my": "Myanmar (Burmese)",
    "nhe": "Nahuatl (Eastern Huasteca)",
    "ndc-zw": "Ndau",
    "nde": "Ndebele (South)",
    "new": "Nepalbhasa (Newari)",
    "ne": "Nepali",
    "no": "Norwegian",
    "nus": "Nuer",
    "ny": "Nyanja (Chichewa)",
    "oci": "Occitan",
    "or": "Odia (Oriya)",
    "om": "Oromo",
    "oss": "Ossetian",
    "pag": "Pangasinan",
    "pap": "Papiamento",
    "ps": "Pashto",
    "fa": "Persian",
    "pl": "Polish",
    "por": "Portuguese (Portugal)",
    "pt": "Portuguese (Portugal, Brazil)",
    "pa": "Punjabi",
    "pa-arab": "Punjabi (Shahmukhi)",
    "kek": "Q'eqchi'",
    "qu": "Quechua",
    "rom": "Romani",
    "ro": "Romanian",
    "run": "Rundi",
    "ru": "Russian",
    "sme": "Sami (North)",
    "sm": "Samoan",
    "sag": "Sango",
    "sa": "Sanskrit",
    "sat": "Santali",
    "gd": "Scots Gaelic",
    "nso": "Sepedi",
    "sr": "Serbian",
    "st": "Sesotho",
    "crs": "Seychellois Creole",
    "shn": "Shan",
    "sn": "Shona",
    "scn": "Sicilian",
    "szl": "Silesian",
    "sd": "Sindhi",
    "si": "Sinhala (Sinhalese)",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "es": "Spanish",
    "su": "Sundanese",
    "sus": "Susu",
    "sw": "Swahili",
    "ssw": "Swati",
    "sv": "Swedish",
    "tl": "Tagalog (Filipino)",
    "tah": "Tahitian",
    "tg": "Tajik",
    "ber-latn": "Tamazight",
    "ber": "Tamazight (Tifinagh)",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "tet": "Tetum",
    "th": "Thai",
    "bod": "Tibetan",
    "ti": "Tigrinya",
    "tiv": "Tiv",
    "tpi": "Tok Pisin",
    "ton": "Tongan",
    "ts": "Tsonga",
    "tsn": "Tswana",
    "tcy": "Tulu",
    "tum": "Tumbuka",
    "tr": "Turkish",
    "tk": "Turkmen",
    "tuk": "Tuvan",
    "ak": "Twi (Akan)",
    "udm": "Udmurt",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ug": "Uyghur",
    "uz": "Uzbek",
    "ven": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "war": "Waray",
    "cy": "Welsh",
    "wol": "Wolof",
    "xh": "Xhosa",
    "sah": "Yakut",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yua": "Yucatec Maya",
    "zap": "Zapotec",
    "zu": "Zulu",
}


def guess_lang_code(query: str):
    """
    Guess a language code using direct comparison and
    fuzzy search based on a query.

    Examples:
    - `guess_lang_code("eng")` returns `"en"`;
    - `guess_lang_code("spanihs")` returns `"es"`;
    - `guess_lang_code("qwerty")` returns `None`.
    """
    query = query.strip().lower()

    # Direct comparison with keys
    if query in LANGUAGES:
        return query

    # Fuzzy search on keys
    if 2 <= len(query) <= 4:
        close = difflib.get_close_matches(
            query, list(LANGUAGES.keys()), n=1, cutoff=0.6)
        if close:
            return close[0]

    # Fuzzy search on values
    close = difflib.get_close_matches(
        query, list(LANGUAGES.values()), n=1, cutoff=0.6)
    if close:
        name_match = close[0].lower()
        for code, name in LANGUAGES.items():
            if name.lower() == name_match:
                return code

    return None
